; This file is automatically generated
; (see binding-generator/gen.rb)

(c-define-struct SDL_CommonEvent
    (type Uint32)
    (timestamp Uint32))

(c-define-struct SDL_WindowEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (event Uint8)
    (padding1 Uint8)
    (padding2 Uint8)
    (padding3 Uint8)
    (data1 Sint32)
    (data2 Sint32))

(c-define-struct SDL_KeyboardEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (state Uint8)
    (repeat Uint8)
    (padding2 Uint8)
    (padding3 Uint8)
    (keysym SDL_Keysym))

(c-define-struct SDL_MouseMotionEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (which Uint32)
    (state Uint32)
    (x Sint32)
    (y Sint32)
    (xrel Sint32)
    (yrel Sint32))

(c-define-struct SDL_MouseButtonEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (which Uint32)
    (button Uint8)
    (state Uint8)
    (padding1 Uint8)
    (padding2 Uint8)
    (x Sint32)
    (y Sint32))

(c-define-struct SDL_MouseWheelEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (which Uint32)
    (x Sint32)
    (y Sint32))

(c-define-struct SDL_JoyAxisEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (axis Uint8)
    (padding1 Uint8)
    (padding2 Uint8)
    (padding3 Uint8)
    (value Sint16)
    (padding4 Uint16))

(c-define-struct SDL_JoyBallEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (ball Uint8)
    (padding1 Uint8)
    (padding2 Uint8)
    (padding3 Uint8)
    (xrel Sint16)
    (yrel Sint16))

(c-define-struct SDL_JoyHatEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (hat Uint8)
    (value Uint8)
    (padding1 Uint8)
    (padding2 Uint8))

(c-define-struct SDL_JoyButtonEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (button Uint8)
    (state Uint8)
    (padding1 Uint8)
    (padding2 Uint8))

(c-define-struct SDL_JoyDeviceEvent
    (type Uint32)
    (timestamp Uint32)
    (which Sint32))

(c-define-struct SDL_ControllerAxisEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (axis Uint8)
    (padding1 Uint8)
    (padding2 Uint8)
    (padding3 Uint8)
    (value Sint16)
    (padding4 Uint16))

(c-define-struct SDL_ControllerButtonEvent
    (type Uint32)
    (timestamp Uint32)
    (which SDL_JoystickID)
    (button Uint8)
    (state Uint8)
    (padding1 Uint8)
    (padding2 Uint8))

(c-define-struct SDL_ControllerDeviceEvent
    (type Uint32)
    (timestamp Uint32)
    (which Sint32))

(c-define-struct SDL_TouchFingerEvent
    (type Uint32)
    (timestamp Uint32)
    (touch-id SDL_TouchID)
    (finger-id SDL_FingerID)
    (x float)
    (y float)
    (dx float)
    (dy float)
    (pressure float))

(c-define-struct SDL_MultiGestureEvent
    (type Uint32)
    (timestamp Uint32)
    (touch-id SDL_TouchID)
    (d-theta float)
    (d-dist float)
    (x float)
    (y float)
    (num-fingers Uint16)
    (padding Uint16))

(c-define-struct SDL_DollarGestureEvent
    (type Uint32)
    (timestamp Uint32)
    (touch-id SDL_TouchID)
    (gesture-id SDL_GestureID)
    (num-fingers Uint32)
    (error float)
    (x float)
    (y float))

(c-define-struct SDL_DropEvent
    (type Uint32)
    (timestamp Uint32)
    (file char*))

(c-define-struct SDL_QuitEvent
    (type Uint32)
    (timestamp Uint32))

(c-define-struct SDL_OSEvent
    (type Uint32)
    (timestamp Uint32))

(c-define-struct SDL_UserEvent
    (type Uint32)
    (timestamp Uint32)
    (window-id Uint32)
    (code Sint32)
    (data1 void*)
    (data2 void*))

(c-define-struct SDL_SysWMEvent
    (type Uint32)
    (timestamp Uint32)
    (msg SDL_SysWMmsg*))

(c-define-struct SDL_Keysym
    (scancode SDL_Scancode)
    (sym SDL_Keycode)
    (mod Uint16)
    (unused Uint32))

(c-define-struct SDL_Color
    (r Uint8)
    (g Uint8)
    (b Uint8)
    (a Uint8))

(c-define-struct SDL_Palette
    (ncolors int)
    (colors SDL_Color*)
    (version Uint32)
    (refcount int))

(c-define-struct SDL_Point
    (x int)
    (y int))

(c-define-struct SDL_Rect
    (x int)
    (y int)
    (w int)
    (h int))

(c-define-struct SDL_Surface
    (flags Uint32)
    (format SDL_PixelFormat*)
    (w int)
    (h int)
    (pitch int)
    (pixels void*)
    (userdata void*)
    (locked int)
    (lock-data void*)
    (clip-rect SDL_Rect)
    (map struct SDL_BlitMap*)
    (refcount int))

